### ISSUE TITLE
Caddy proxy: wrong encoding (escape single and double quotes) in raw_config

### ISSUE THREAD

**Issue by regystro** [bestlibre/hassio-addons#100]
Hi. It's not possible to use single and/or double quotes, since the parser encodes them to htmlentities:
```
 "raw_config": [
    {
      "line": "# Single and double quote test: \" ' &quot; &apos; \u0022"
    }
  ]
```
Then if you enter the container and `cat /tmp/caddy.conf`, this is what you get:

`# Single and double quote test: &quot; &#x27; &amp;quot; &amp;apos; &quot;`

I think that at least `\"` should be encoded as `"`.
Could you please fix this in order to be able to escape and write double quotes to the raw_config section? That way we'll be able to use spaces in some config options.

Thank you

**Comment by bestlibre** [comment]
I will look at it.

**Comment by bestlibre** [comment]
Should be fixed with last version
