### ISSUE TITLE
caddy_proxy does not appear in the list of addons

### ISSUE THREAD

**Issue by kegra** [bestlibre/hassio-addons#101]
18-12-22 19:55:59 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/53caca22/caddy_proxy/config.json: expected string or buffer @ data['schema']['vhosts'][0]['paths'][0]. Got {'path': 'str', 'remote': 'str?', 'port': 'str'}

**Comment by bestlibre** [comment]
I see what is the cause and I think that I have a solution. I will try to fix ASAP

**Comment by bestlibre** [comment]
Should be fixed
