### ISSUE TITLE
Caddy not working after update

### ISSUE THREAD

**Issue by olkal** [bestlibre/hassio-addons#110]
Hi, I'm running the Caddy add-on with HassOS 2.10 on Odroid C2, HA version 0.89.2.  I can no longer reach Homeassistant from outside my local network. The complete Caddy log looks like this:

`/run.sh: line 16:    11 Done                    echo "{\"vhosts\":[{\"vhost\":\"$homeassistant\", \"port\":\"8123\"}]}"
        12 Segmentation fault      (core dumped) | python3 /mustache.py /templates/vhost.mustache - >> /tmp/caddy.conf`

I think that the problem started when I updated Caddy to 0.11.5 a few days ago.
Any ideas?

**Comment by bestlibre** [comment]
I will look into it ASAP. Can you give me the Arch type of your install? Armv7, aarch64 ?

**Comment by olkal** [comment]
Great :) It's aarch64.

**Comment by bestlibre** [comment]
Can you try with the last version ?

**Comment by olkal** [comment]
The last version fixed the issue, many thanks!
