### ISSUE TITLE
Syncthing addon no longer starts

### ISSUE THREAD

**Issue by haberda** [bestlibre/hassio-addons#136]
[monitor] 07:59:30 INFO: Starting syncthing
[start] 07:59:30 INFO: syncthing v1.2.2 "Fermium Flea" (go1.12.9 linux-amd64) teamcity@build.syncthing.net 2019-08-15 13:51:09 UTC
[start] 07:59:30 WARNING: Failed to initialize config: config file version (30) is newer than supported version (29). If this is expected, use -allow-newer-config to override.
[monitor] 07:59:30 INFO: Syncthing exited: exit status 1
[monitor] 07:59:31 WARNING: 4 restarts in 4.169991612s; not retrying further

Above is the error log from the addon. This started to occur without any configuration changes.

**Comment by theCheek** [comment]
just ran into it myself. Where can we add the flag -allow-newer-config to try to workaround this?

**Comment by bestlibre** [comment]
This is probably because syncthing auto update, the version of the config file as increased and the container restarted, downgrading syncthing. I will try to update the addon ASAP.

**Comment by bestlibre** [comment]
Should be fixed with the new version. Can you confirm ?

**Comment by theCheek** [comment]
Sorry I uninstalled it already as I decided to install it as a docker container instead. Hopefully @haberda can help you confirm if its fixed. Thanks for your fast bug fix though!

**Comment by haberda** [comment]
I can't seem to pull the new version. However, I just blew away my config and it works again.

**Comment by marecabo** [comment]
I reinstalled the addon and it continued to work for a few days. Syncthing even updated itself successfully after the reinstall.

However, now it stopped working again after I rebooted the host of Home Assistant.

**Comment by MichaelBitard** [comment]
You updated the docker image but forgot to update the addon version I think. I'll create a PR

**Comment by bestlibre** [comment]
Good catch ! The commit was blocked on my computer. Thanks

**Comment by haberda** [comment]
This appears to be fixed! Thanks!
