### ISSUE TITLE
Support subdir for proxy service

### ISSUE THREAD

**Issue by bestlibre** [bestlibre/hassio-addons#14]
To be able to proxy a service install in a subdirectory. 

The configuration would look like : 
````
{"remote" : "ip",
 "port": "8082",
 "vhost":"blog.mydomain.com",
 "subdir":"wordpress"} 
````

**Comment by parneli** [comment]
This would be useful, the full service can do this I am hoping it wouldn't be much work to add this in?

**Comment by bestlibre** [comment]
Should be done with next release
