### ISSUE TITLE
Missing option certname in vhosts for dictionary value @ data['options'].

### ISSUE THREAD

**Issue by kozoke** [bestlibre/hassio-addons#15]
Hi,
Great stuff - thanks for your work on this. 

I'm having trouble configuring NGINX for hadashboard (related to home assitsant). 
Error message:
Missing option certname in vhosts for dictionary value @ data['options']. Got {'vhosts': [{'default_server': False, 'port': '3030', 'vhost': 'hassio.sylvanmaker.com'}]}
}

myconfig:
{
  "vhosts": [
    {
      "default_server": false,
      "port": "3030",
      "vhost": "hassio.sylvanmaker.com"
    }
  ]
}

As I look at your code, it should be taking the absence of "cert name" in my config and proceeding but for some reason it won't let me save and start.  I swore this worked just 5 days ago then seemed to stop working. Any ideas?

Thanks!

**Comment by bestlibre** [comment]
There was a breaking change in one of the last hassio update regarding optional configuration values. I will need to change the config.json to be compatible. I don't if I'll be able to do it before Monday.

**Comment by kozoke** [comment]
Thanks for the update.  Good to know it isn't something i'm doing wrong.  I'll await an update.

**Comment by bestlibre** [comment]
It should be ok now
