### ISSUE TITLE
Grafana Options wont save

### ISSUE THREAD

**Issue by paul2nz** [bestlibre/hassio-addons#16]
I am a noob and not sure if i am doing something wrong when trying to add variables in the options window. I need to access grafana using https://mydomain.duckdns.org:3000 
Below is the variable I place in the options box. The save button works, but once I restart garafna the variables disappear and revers back to default.

{
"protocol": "https",
"domain": "mydomain.duckdns.org",
"root_url": "https://mydomain.duckdns.org:3000",
"cert_file": "fullchain.pem",
"cert_key": "privkey.pem"
}

Thanks in advance.

**Comment by ciotlosm** [comment]
My options box only contains
 {
  "env_var": []
}

Maybe it got simplified and not it doesn't require the options.

**Comment by ciotlosm** [comment]
This issue should be closed
