### ISSUE TITLE
Grafana multiarch disappeared from list?

### ISSUE THREAD

**Issue by DarkFox** [bestlibre/hassio-addons#18]
Currently, the Grafana multiarch container isn't showing up in the available add-ons list. I seem to remember that it was there last night.

**Comment by bestlibre** [comment]
It should be fixed. Thanks for the report.

**Comment by DarkFox** [comment]
Trying to install it, I get this in the hassio supervisor logs:

> 17-10-20 09:31:06 ERROR (SyncWorker_3) [hassio.dock.interface] Can't install bestlibre/amd64-nextcloud:4.4.3-3 -> 404 Client Error: Not Found ("manifest for bestlibre/amd64-nextcloud:4.4.3-3 not found").

**Comment by bestlibre** [comment]
I sometimes had yhis problem after a bad commit. I haven't yet found a way to reliably fix it. Can you try to : 
- refresh the addon list, then try to update ;
- if it doesn't work, restart the supervisor then try to update,
- if it still does'nt work, restart the host then try to update ?

Or if you have an idea how to clean the repository cache...

**Comment by DarkFox** [comment]
Removing and re-adding the repo address fixed it. 👍

**Comment by bestlibre** [comment]
Thanks ! Haven't though of that
