### ISSUE TITLE
cant get at configfile

### ISSUE THREAD

**Issue by sean666888** [bestlibre/hassio-addons#2]
I am unable to access the config file to enable authentication

**Comment by bestlibre** [comment]
For which addon ?

**Comment by sean666888** [comment]
influxdb

**Comment by bestlibre** [comment]
Authentication is not possible right now. I haven't got the need since my influxdb instance is not exposed to the world, only internal network. I will try to look at it.

**Comment by sean666888** [comment]
thanks

**Comment by bestlibre** [comment]
It should be possible with the latest version (using environment variable)
