### ISSUE TITLE
nextcloud volumes option missing

### ISSUE THREAD

**Issue by nephe** [bestlibre/hassio-addons#25]
Hi, 
under hassio addon options you cannot specify volumes which seems to be required for proper configuration on nextcloud, for exmaple config.php. Could you add that option?

**Comment by bestlibre** [comment]
The nexcloud dir, wich in the upstream image is at `/var/www` is moved in `/data/www`. The `config.php` file is in this folder. It should be enough to permit nexcloud configuration.

**Comment by nephe** [comment]
I can't find neither www directory nor config.php. Addon is running and is accessible.
Also NEXTCLOUD_DATA_DIR variable is not working. Data is stored in other place. I think this variable was used in other docker container for nextcloud but it is not working with official one.

**Comment by bestlibre** [comment]
Nextclood is not supported anymore
