### ISSUE TITLE
Request: Phlex server

### ISSUE THREAD

**Issue by Jolanrensen** [bestlibre/hassio-addons#27]
As you have made several awesome server plugins, I'd like to make a request. If you know Plex, you might know [Phlex tv](https://github.com/d8ahazard/Phlex) which requires a php server to run and allows you to control Plex using voice commands from Google assistant and Alexa. It can installed via docker but I wasn't able to get it to work. Since you have some more experience, maybe you could have a look at it?
Thanks in advance!

**Comment by anthonyangel** [comment]
I've got Phlex set up with the hassio addon from https://github.com/bezmi/addon-phlex, and have it working with caddy.

-----------------------------------------------------
Phlex config:
```
{
  "port": 5666,
  "fastcgiport": 9123,
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```
-----------------------------------------------------
Caddy config:
```
{
  "homeassistant": "hass.mydomain.co.uk",
  "vhosts": [
    {
      "vhost": "phlex.mydomain.co.uk",
      "port": "5666",
      "remote": ""
    }
  ],
  "raw_config": [],
  "email": "mail@mydomain.com"
}
```
