### ISSUE TITLE
Syncthing version doesn't exist

### ISSUE THREAD

**Issue by snarby2013** [bestlibre/hassio-addons#3]
Trying to install Syncthing but get an error ERROR (SyncWorker_12) [hassio.dock] Can't install bestlibre/armhf-syncthing:0.14.33 -> 404 Client Error: Not Found ("manifest for bestlibre/armhf-syncthing:0.14.33 not found").

**Comment by bestlibre** [comment]
It should work now, there was a glitch with the build system. Version 0.14.36 is running on my pi.
