### ISSUE TITLE
Not an issue - request for help on influxDB and grafana

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#30]
setting this up on Hass.io , there are a couple of simple things , that i was not able to complete 
1 - set the  admin user and password on influxDB , Ssh throws an error and there is no way to get rid of it -
when i send: curl -i -XPOST http://192.168.0.xx:8086/query  --data-urlencode "q= CREATE USER “admin” WITH PASSWORD ‘passwd’ WITH ALL PRIVILEGES"

the output is 
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 7e767fd8-d3c7-11e7-8007-000000000000
X-Influxdb-Version: 1.3.7
Date: Mon, 27 Nov 2017 23:05:43 GMT
Content-Length: 83

{"error":"error parsing query: found “, expected identifier at line 1, char 13"}

AND the other problem , how to set the user and pass on grafana? , as it says is going to send an email, but on the docker version i think this do not apply .

thanks in advance !

**Comment by ciotlosm** [comment]
Replace “admin” with ‘admin’ and try again

**Comment by gnkarn** [comment]
thanks for your answer ,

same error message

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 98c7964c-d441-11e7-863b-000000000000
X-Influxdb-Version: 1.3.7
Date: Tue, 28 Nov 2017 13:39:45 GMT
Content-Length: 83

{“error":"error parsing query: found ‘, expected identifier at line 1, char 13"}

**Comment by macrojames** [comment]
Replace it with " on your keyboard. It looks like copy & paste from a website that formatted the quotes differently.

**Comment by ciotlosm** [comment]
Maybe if I post in code block it might work
```
curl -i -XPOST http://192.168.0.xx:8086/query --data-urlencode "q= CREATE USER 'admin' WITH PASSWORD 'passwd' WITH ALL PRIVILEGES"
```

**Comment by SubhashPatel** [comment]
try this
`curl -i -XPOST http://localhost:8086/query --data-urlencode "q= CREATE USER admin WITH PASSWORD 'Init@123' WITH ALL PRIVILEGES"`
