### ISSUE TITLE
How to configure Grafana + influx DB - properly  ?

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#31]
i have followed the docs, and enabled influx DB  configuration  on config yaml file , there i have  listed some ids i need to be charted on grafana , but when  on the grafana dashboard config page , none of the tags i enable appear on the drop down list , and there are many others that should be there .

So , my question is , how to make influxDB to honor what tis on the configuration file ?

other question , is how to i know the sample time for each variable , and data base status ?

-----
sample config 

influxdb:
  host: 192.168.0.60
  port: 8086
  database: home_assistant
  # username: !secret influxdb_name
  # password: !secret influxdb_pass
#   ssl: true
#   verify_ssl: true
  default_measurement: state
#   # exclude:
#   #   entities:
#   #      - entity.id1
#   #      - entity.id2
#     # domains:
#     #    - automation
  include:
    entities:
      - sensor.weather_temperature
      - sensor.temp_temperature
      - sensor.weather_pressure
      - sensor.ram_used
      - sensor.ram_available
      - sensor.owm_temperature
      - sensor.solar_angle
      - sensor.disk_free_home
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_apparent_temperature

    domains: 
      - automation
      - switch
      - sensor   
tnakyou

note : im not using user and pass , as the command to make the new user dont work, but without validation de data base is working ...

**Comment by ciotlosm** [comment]
Check that your entities are not grouped under the corresponding domain. For example temperature under "C" where you have to filter out based on entity_id

See my example below:

![screen shot 2017-12-02 at 22 57 31](https://user-images.githubusercontent.com/7738048/33519674-38e8e6dc-d7b4-11e7-88fa-bb8fc12d80c8.png)

**Comment by gnkarn** [comment]
i found it , there are some measure that don't appear , because there is nothing on the drop down menu to select .

for example, temperature , the unit "°C" , was not on the menu at all , as soon as i pasted it , i was able to access to the entity Ids, .

So i guess , the question that remains , is : what is included by default on that menu?, and if it is something that we can do as users to better organize it , so it can have some meaning .

thanks a lot ,  a was able to make a lot of progress with your help .

**Comment by ciotlosm** [comment]
That is harder to answer. The internal setup of your influxdb structure is up to home-assistant. I guess this question is better asked on discord or the home-assistant forum.
