### ISSUE TITLE
100 meassures limit ?

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#32]
is it possible that either grafana or influxDB have a limit on 100 tag names?

grafana is showing me , only 100 ids ,  if it is , then how to configure which ones to include on the data base ? , i have tryied the include option on config , but is not making any difference .

appreciate your response ,.
tks

**Comment by ciotlosm** [comment]
There shouldn't be any limit. 
Hassio should be sending all metrics, influxdb should not have limits, and grafana should show everything inside your datasource. Of course the autocomplete popup has limitations. 

Where do you see the 100 limit?

**Comment by gnkarn** [comment]
i counted the number of select options on the dropdown menu ( Metrics , FROM:   ),.
i don't understand where that list came from as there are mixed elements , units of measure and  IDs, groups  , but most important the list is incomplete.

for example i do have sensor.dark_sky_apparent_temperature , and other metrics on hassio, but on grafana , there are only sensor.dark_sky_icon ; and sensor.dark_sky_summary .
And many other examples like that .

so , there may be some "trick" or reason why they do not appear on grafana (?)
in this case these are all the monitored conditions:
monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_probability
    - apparent_temperature
    - minutely_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - uv_index

only the first two appear on grafana .. and can't understand why.

- regards

**Comment by ciotlosm** [comment]
It all comes up to how home-assistant groups measurements in influxdb. Many sensors are grouped by their measurement (like % for example). I know this doesn't up completely to make sense where stuff is, but at least it helps to explore other fields to find your missing sensor data.

**Comment by gnkarn** [comment]
realize that is tricky to find the tags , but they are there , so not a real issue , thanks
