### ISSUE TITLE
Support for shared `/dev/snd` via either `ipc` or `v` parameter with docker run

### ISSUE THREAD

**Issue by mbrownnycnyc** [bestlibre/hassio-addons#38]
Hello,

I'd like to request support for sharing of `/dev/snd` across containers.  For instance, if I play anything with `mopidy` it locks `/dev/snd` and then the hass.io container can't access the device.

The solution for this is to use `--ipc` or `-v` to share memory resources.

Is this something you'd consider?

I've opened [a ticket](https://github.com/home-assistant/hassio/issues/281) with the hass.io project for the same, but I do think you'd need to make the change as well.

Thanks

**Comment by bestlibre** [comment]
Should be done with the next build. Sorry for the delay
