### ISSUE TITLE
hass.io and Mopidy: Cmd('git') failed due to: exit code(128)

### ISSUE THREAD

**Issue by Jenscaasen** [bestlibre/hassio-addons#45]
Hi,
when trying to install the mopidy addon i get the following error. What can i do to install the mopidy add-on into hass.io?

18-02-01 18:02:07 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/bestlibre/hassio-addons/tree/master/mopidy repository
18-02-01 18:02:07 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/bestlibre/hassio-addons/tree/master/mopidy repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --recursive -v https://github.com/bestlibre/hassio-addons/tree/master/mopidy /data/addons/git/5708a1bf
  stderr: 'Cloning into '/data/addons/git/5708a1bf'...
remote: Not Found
fatal: repository 'https://github.com/bestlibre/hassio-addons/tree/master/mopidy/' not found

**Comment by bestlibre** [comment]
What have you set in the repository address in the addon repository setting page ?

**Comment by Jenscaasen** [comment]
My fault, did not have to add
https://github.com/bestlibre/hassio-addons/tree/master/mopidy/
but
https://github.com/bestlibre/hassio-addons/
