### ISSUE TITLE
Caddy Proxy Timeout Error

### ISSUE THREAD

**Issue by onetruthonefault** [bestlibre/hassio-addons#47]
Below is the log I'm getting when I run Caddy.

**Setup**
```
Hass.io: 0.62.1
System: Raspberry PI 3
DuckDNS Enabled
Caddy: 0.10.10-2
```

**Caddy Config**
```
{
  "homeassistant": "domain.domain",
  "vhosts": [],
  "raw_config": [],
  "email": "email@email"
}
```

**Log**
Below, domain and ipaddr are the expected domain and IP address for my setup.  I'm getting an acme connection timeout.
```
starting version 3.2.4
2018/02/08 00:50:34 [domain.domain] failed to get certificate: acme: Error 400 - urn:acme:error:connection - Fetching http://domain.domain/.well-known/acme-challenge/ebP...: Timeout
Error Detail:
	Validation for domain.domain:80
	Resolved to:
		ipaddr.ipaddr.ipaddr.ipaddr
	Used: ipaddr.ipaddr.ipaddr.ipaddr
Activating privacy features...
```

**Comment by onetruthonefault** [comment]
_Note: I had this working before on my Raspberry PI 2, with Hass.io 0.56.1.  The Caddy version is older as well (about 3 months)._

**Comment by TomerFi** [comment]
I have the same issue.
I work with version 0.63.3 for a long time and it was working great until today when I started receiving this error.
But I think it's an HA error and not by Caddy Proxy, seeing that I also use the duckdns component to update my ip address and I've noticed my ip isn't being updated to the duckdns servers.
It looks like my HA has problems with outgoing traffic...

**Comment by TomerFi** [comment]
Solved.
My certificate was due for renewal, as it turns out, I needed to open both ports configured in the add on for the renewal of the certificate, after it's renewed, I've closed back port 80 and everything works well.

**Comment by onetruthonefault** [comment]
I already renewed my certificate.  But, the issue persists, unfortunately.  Reverting with the exact same settings on my older setup works just fine.
