### ISSUE TITLE
Caddy: not a valid value for dictionary value @ data['options']

### ISSUE THREAD

**Issue by fbartels** [bestlibre/hassio-addons#49]
Hi, 
I am trying to configure your caddy add-on in hassio, but I always get below error:

```
not a valid value for dictionary value @ data['options']. Got {'homeassistant': 'homeassistant.domain.tld', 'vhosts': [], 'raw_config': [], 'email': None}
```

This even happens when I reset the config back to default as seen above. Is this a backwards incompatible change in hassio 0.63.2?

Caddy add-on: v0.10.10-2
Hassio: 0.63.2

**Comment by bestlibre** [comment]
You need to specify an email. Something like 
````
{"homeassistant": "homeassistant.domain.tld", "vhosts": [], "raw_config": [], "email": "email@email.tld"}
````

**Comment by fbartels** [comment]
Ah, indeed. When setting an email there it works. Maybe it could help to include an email in the example config. Since it was set to null there I thought I could just take this value for my configuration as well.

**Comment by bestlibre** [comment]
I prefer to add a warning in the documentation. There is a risk that the default value could be use (there is no email validation in the letsencrypt certificate creation).

**Comment by KenwoodFox** [comment]
This is still not working for me? Im not sure what im missing, Ive installed the addon on a fresh install, where do i add an email?

**Comment by bestlibre** [comment]
You need to have an email option in your configuration. See the example above. You can also send me your configuration (edited to remove personal data) if it doesn't work.

**Comment by mkerner** [comment]
I'm receiving this same error with any config file that has vhosts in it. If I delete all my vhosts the config will save.  This was my first attempt to restart caddy after quite some time of it being very stable.

HA: 0.87.1 

I'm happy to send you my config if that helps.
