### ISSUE TITLE
A little help please

### ISSUE THREAD

**Issue by droidforever** [bestlibre/hassio-addons#5]
I am a complete n00b and have no idea what I'm doing.  I am trying to use certbot addon for Hassio.  My Hassio instance runs in a docker container inside Debian Jessie Linux.  I am unable to get NGINX to start.  Here is the way I have my config done.  Please, if you would, correct whatever I'm doing wrong.  

{
  "vhosts": [
    {
      "vhost": "sub1.mydomain.com",
      "default_server": true,
      "certname": "rpi",
      "port": "8123"
    },
    {
      "remote": "192.168.10.10",
      "vhost": "sub2.jdmguide.com",
      "certname": "nas",
      "port": "443"
    }
  ]
}

In Cerbot:

{
  "debug": false,
  "email": "myemail",
  "certificats": [
    {
      "name": "hass",
      "domains": "sub1.mydomain.com"
    }
  ],
  "ssl_only": false
}

I'm sure there are several errors here.  Thank you in advance for your assistance.

**Comment by bestlibre** [comment]
Names in nginx conf and in certbot must match. For each name in nginx you must have one in certbot. You can also use only one name for both subdomains.

You can also try the caddy proxy add-on, which should be easier to set up. It is self sufficient and doesn't need the certbot add-on to obtain certificates from let's encrypt.

**Comment by jebentancour** [comment]
Hello, I have another problem

[emerg] 20#20: SSL_CTX_load_verify_locations("/ssl/letsencrypt/live/hass/chain.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory

**Comment by bestlibre** [comment]
Do you use both the nginx proxy and the certbot add-ons ?

**Comment by jebentancour** [comment]
No, I put the two .pem files you specify on the rezadme in the rigth folder. I wasnt able to generte the certificates with certbot, I opened the ports 443, 80, and 10443 with no luck

**Comment by ciotlosm** [comment]
@jebentancour Easiest way is to expose first nginx without certificate on port 80 and configure certbot to request a certificate. The nginx addon will allow certbot validation file to be expoed on port 80 with proper path to generate the certificates. After certificates are generated, just enable ssl.

To disable ssl just remove certname.
Make sure you port 80 is forwarded correctly on the router that faces your internet. YOu can leave port 80 on after you enable ssl (adding back correct certname used in certbot) as that will cause 80 to be redirected to 443 by default.

**Comment by penright** [comment]
I don't mean to cross post but being new I am not sure if I post in a closed issue if anyone would see it. I think I still on topic as I need some help. :-)

@ciotlosm You closed #35 what did you do to fix it?

Do I need to request that Nginx option "client_max_body_size" be exposed via the HASS.IO options? 

I am getting this ....
2018/01/18 07:02:22 [error] 27#27: *34229 client intended to send too large body: 7176858 bytes, client: 69.x.x.x, server: nas.xxxxxxx.net, request: "POST /3.0/index.php?explorer/fileUpload&path=%2FUser%2Fpenright%2Fhome%2FMovies%2FHomeMovies%2F HTTP/2.0", host: "nas.xxxxx.net", referrer: "https://nas.xxxxxx.net/3.0/index.php?/explorer&type=iframe&path="

**Comment by ciotlosm** [comment]
@bestlibre this issue should be closed. Maybe you can look at #35 as that is still not working. Happy to reopen that.
