### ISSUE TITLE
Grafana addon for hass.io for Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Pannonicus** [bestlibre/hassio-addons#51]
Hi!
Title says it all, would it be possible to make the addon work for the RPi Z w or is there another repo for the pi zero w that i am not aware of?

Thanks!

**Comment by bestlibre** [comment]
It should be working on the pi zero as it is. What error, if any, do you have when installing/starting ?

**Comment by Pannonicus** [comment]
Hi, unfortunately the Log on the Addon-Page doesn't provide any output. It's basically the same behavior for Grafana and Influx. I can install the Add-Ons and click start, then Grafana seems to start. But after refreshing the page or doing anything else, the addon is shown as inactive. (all other addons but these two seem to work tough). 

Also the readme of the Grafana-Addon says "This addon provide grafana for the armhf architecture (rpi 2 - 3) and amd64." - so I figured this might be the issue. 

I had Grafana and InfluxDB runing on a PiZeroW on a previous Home Assistant Installtion. So it should work somehow.  For Grafana on the old installation i followed the Rp1b instructions here:
[https://github.com/fg2it/grafana-on-raspberry/wiki](url)

I am a total newbie, so but I managed to install Grafana  and Influx on the old version with the following commands:
Influx:
`curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/os-release
test $VERSION_ID = "8" && echo "deb https://repos.influxdata.com/debian jessie stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
`
Grafana:
`sudo dpkg --purge grafana
curl -L https://bintray.com/fg2it/deb-rpi-1b/download_file?file_path=main%2Fg%2Fgrafana_4.1.2-1487023486_armhf.deb -o /tmp/grafana_4.1.2_armhf.deb
sudo dpkg -i /tmp/grafana_4.1.2_armhf.deb
`
Maybe this helps. 

**_## (In any case, this is not a big issue for me. So it might not be worthwhile to look into that any further. I plan to upgrade to the new RP3B+ once Hassio supports it. :-D )_**
