### ISSUE TITLE
Snapclient not starting

### ISSUE THREAD

**Issue by Jenscaasen** [bestlibre/hassio-addons#52]
Hi,
i am running the snapserver and mopidy with success, thanks for that realy easy configuration :-)
Using it from another rpi with a snapclient works too. Now i want to install the snapclient on the hassio RPI to let it output music too. But the snapclient wont start. I guess it has to do with the config, which in default says "{ }", but when i click "save" it says it would not be valid. Do you have a sample config? I want to add -h 192.168.0.18, but i have no idea about the syntax.

Thanks in advance!

**Comment by bestlibre** [comment]
Try with : 
````
{
  "host": "192.168.0.18"
}
````

**Comment by Jenscaasen** [comment]
It works! Thank you so so much! Now we finally have music in the living room, and one spare Raspberry to bring the music into the kitchen as well =) 
Thanks for theese great add-ons!
