### ISSUE TITLE
Question: how to configure https for grafana on HASS.io env vars ?

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#56]
i tryed , to add the certificate files to grafana in different ways ,  but was not able to make grafana to find it .

the last test was by enabling https, 
and add

{
      "name": "cert_key",
      "value": "/ssl/privkey.pem"
    },
    {
      "name": "cert_file",
      "value": "/ssl/fullchain.pem"
    }

to the configuration  , ( tried with and without /ssl , with and without hassio/ssl/   ... etc ) 
even when  it takes the env variables ok , but it seams they need to be added other way  , as grafana always claims that the cert file can not be empty .... ( and it is not ) .

it would be very helpful to add , how to configure this critical part , to make grafana access secure from outside .

thank you

**Comment by bestlibre** [comment]
How do you get the certificate files ? If they are located in the ssl folder of hassio (accessible with the samba plugin for exemple), it should work with the config you have given.

To have grafana exposed with ssl, you can also use one of my proxy plugin (caddy or nginx).

**Comment by gnkarn** [comment]
i ended installing caddy , and it works great , thank you
