### ISSUE TITLE
Nextcloud hassio addon issue

### ISSUE THREAD

**Issue by bachulator** [bestlibre/hassio-addons#58]
Hassio: 0.65.5

Trying install nextcloud addon finishes with the error:
[hassio.docker.interface] Can't install bestlibre/armhf-nextcloud:12.0.3 -> 404 Client Error: Not Found ("no such image: bestlibre/armhf-nextcloud:12.0.3: No such image: bestlibre/armhf-nextcloud:12.0.3"

Are there any chance the addon might be supported in future and if so can it upgraded to current version of nextcloud 13.0.X

Thanks.

**Comment by bestlibre** [comment]
I do not use it anymore, and do not have a lot of spare time. I will try to have a look. If it's easy to fix I'll do it.

**Comment by bachulator** [comment]
Thanks, that would be really cool to have...

**Comment by bachulator** [comment]
A side question. Since you mentioned you are not using this addon anymore, may I ask what solution do you use for sharing purposes?

**Comment by bestlibre** [comment]
I'm using syncthing to share files between my devices. To share with other persons I use one of dropbox/gdrive/box/hubic depending of the file size and recipient.

**Comment by bachulator** [comment]
Thanks. Already installed and tried syncthing - nice p2p based solution. The only thing that bothers me that sync process of the app on Android is not integrated to general sync workflow but runs as seporated process which cold be killed by battery management. And yes sharing between devices is an issue.

**Comment by bestlibre** [comment]
Nextclood addon is deprecated.
