### ISSUE TITLE
Does not work with hassio 0.65.6

### ISSUE THREAD

**Issue by kajmaj** [bestlibre/hassio-addons#60]
Does this add work with hassio 0.65.6?
I cannot create database on the first run:
`core-ssh:~# curl -i -XPOST http://192.168.1.107:8086/query --data-urlencode "q=CREATE DATABASE home_assistant"
curl: (7) Failed to connect to 192.168.1.107 port 8086: Connection refused
`
I m connected via ssh.

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
