### ISSUE TITLE
Grafana or influxDb - not updating data correctly ?

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#62]
i know you may receive issues, that are not very specific and you wonder , what  can i do with this ??

this may be another .. , but i like so much the way this works that consider a pitty not to be able solve some of the misterious problems , that impacts its reliability .

this is the issue: i found more than once , that after a raspPI reboot , im not able to access current data anymore from grafana .
Hystoricall data is ok, but  for current time "NO DATA is displayed .

of course tried  restarting grafana, influxdb , and when looking at the logs ,  separately they look ok , but no current data displayed .

the only way , to solve the problem in the past was , to wipeout home assistant data base , and start again, but im resisting doing it again , there should be other way ...

any ideas , are welcomed ,  thanks

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
