### ISSUE TITLE
Mopidy shows wrong version

### ISSUE THREAD

**Issue by jorgeleitao** [bestlibre/hassio-addons#64]
Hi, I'm running HASSIO 0.67.1.

Githum page https://github.com/bestlibre/hassio-addons/tree/master/mopidy is showing version **0.2.3**. But my HASSIO repository manager screen says the Mopidy addon has version **0.1.2**.

After I install the addon I cannot start it. The Javascript console gives an error:

`https://my_hassio.../api/hassio/addons/53caca22_mopidy/start 400 (Bad Request)`

In my system log I get:

```
18-04-25 07:31:39 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/53caca22_mopidy
18-04-25 07:31:39 INFO (SyncWorker_16) [hassio.docker.interface] Pull image bestlibre/armhf-mopidy tag 0.1.2.
18-04-25 07:33:57 INFO (SyncWorker_16) [hassio.docker.interface] Tag image bestlibre/armhf-mopidy with version 0.1.2 as latest
```

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
