### ISSUE TITLE
Problem: cant change data base name - in order to run a 2nd influx on a second RPi3

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#65]
after , changing the db name on config.yaml and creating a new DB with different name than home_assistant , the add-on is still expecting a data base with the home_assistance name .

Why is important : because in my case i have two rp3 and separate data bases on each one , and i need to select either DB from grafana .

if there is a quick fix, or  i may be doing something the wrong way  i will appreciate the comment back . tks

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
