### ISSUE TITLE
Grafana stopped  updating data 

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#67]
i had a working configuration of grafana , indlux db , and an external finance database .

At 00 hs yesterday ,  grafana is not updating data anymore , only data previous to that time is shown.
the same is true for the data on the external DB , that is why i tend to think the problem is related to Grafana instead of the DB or data side .

hassio logs , shows influxdb , is apparently working ok .
but , no data flows to grafana .

i dont know what else to try , 
appreciate if there are ideas of what can a do to debug this type of problem.
----
im not sure if this is related to the problem at all,  but is the only "abnormal"  output i see on the logs
this is from grafana logs:

t=2018-05-11T23:21:21-0300 lvl=eror msg="Failed to get user with id" logger=context userId=1 error="User not found"
t=2018-05-11T23:21:21-0300 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/2/query status=401 remote_addr=192.168.0.1 
time_ms=77 size=26 referer="https://mydomain.duckdns.org/dashboard/db/gnk-home?refresh=30s&orgId=1"

tks

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
