### ISSUE TITLE
Serious issue : Grafana not connecting to hassio after hassio restart

### ISSUE THREAD

**Issue by gnkarn** [bestlibre/hassio-addons#69]
i have been tracking a problem with grafana , influxDB for some time :  influxDB stops receiving "POSTS" from hassio after a hassio restart , other than this all looks Normal.

Even restarting grafana , influxdb , do not solve the problem , and the only way i found to get it back to work is , to reinstall grafana , influxdb, and wiping out the influx db data base , and create it again .

of course , i dont know if this is caused by a problem on influx db , or hassio , but the issue is real , and i would like somebody to suggest what can be done to clear this out . thanks

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
