### ISSUE TITLE
Cannot install mopidy

### ISSUE THREAD

**Issue by 9guiajkbk2** [bestlibre/hassio-addons#7]
When I try to install Mopidy via the add on section in hassio, I get the following error:
`17-09-03 14:10:51 ERROR (SyncWorker_1) [hassio.dock.interface] Can't install bestlibre/armhf-mopidy:0.1.2 -> 404 Client Error: Not Found ("manifest for bestlibre/armhf-mopidy:0.1.2 not found").`
Any help would be appreciated :)!

**Comment by bestlibre** [comment]
There is a problem with the building script. I will look into it ASAP.

**Comment by bestlibre** [comment]
Should be ok
