### ISSUE TITLE
User id changes broke my installation on upgrade to 5.1.4

### ISSUE THREAD

**Issue by mikakesan** [bestlibre/hassio-addons#77]
https://github.com/bestlibre/hassio-addons/blob/25f0c17badad542f55eb4a4b81498c4e63186e96/grafana/Dockerfile#L20

Related to http://docs.grafana.org/installation/docker/#user-id-changes I think the Dockerfile needs to be changed to

`USER 104`

**Comment by ciotlosm** [comment]
Same here, grafana no longer works

**Comment by bestlibre** [comment]
Should be fix with last version (commit   [84381cb](https://github.com/bestlibre/hassio-addons/commit/84381cbfe46b39a31b938dd09309277cc593c732))

**Comment by bestlibre** [comment]
I will close this old issue. Feel free to reopen if needed.
