### ISSUE TITLE
Caddy Proxy version upgrade makes the add-on unresponsive on Raspberry Pi 3

### ISSUE THREAD

**Issue by thibmaek** [bestlibre/hassio-addons#78]
After upgrading to the latest caddy-proxy version this add-on is no longer working.
I can't access my remote domain anymore, which worked fine before the version bump.
Using the following config in Hass.io 0.72.1:

```json
{
  "homeassistant": "x.domain.com",
  "vhosts": [
    {
      "vhost": "a.domain.com",
      "remote": "192.168.1.x",
      "port": "xxxx"
    },
    {
      "vhost": "b.domain.com",
      "remote": "192.168.1.x",
      "port": "xxxx",
      "user": "xxx",
      "pwd": "xxxx"
    },
    {
      "vhost": "c.domain.com",
      "remote": "192.168.1.x",
      "port": "xxxxx",
      "user": "xxxxxxxxxxxxxxx",
      "pwd": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    {
      "vhost": "d.domain.com",
      "remote": "192.168.1.y",
      "port": "xx"
    },
    {
      "vhost": "e.domain.com",
      "remote": "192.168.1.x",
      "port": "xxxx"
    }
  ],
  "raw_config": [],
  "email": "xxxxxxxxxxxxxxxxxx@xxxxxxxxxxxx.com"
}
```

There is no log output from the add-on, nor is there any usable error logging in the supervisor layer.

**Comment by bestlibre** [comment]
It is strange. I'm using the same addon with almost the same conf and it works for me. I do not use the user/pwd anymore. Can you try without those params ?

**Comment by thibmaek** [comment]
Yeah I'll retry this weekend, otherwise I'll just try and downgrade to another Docker image tag for this add-on if that's possible

**Comment by berichta** [comment]
I experienced the same issue, but under different occasions.
The issue happened after switching to HassOS 1.5
Afterwards I removed one vhost after the other and found the one causing the issue:

```
{
  "vhost": "pi-hole.domain.de",
  "port": "8080"
},
```

Changing the port didn't solve the issue. Neither 8080 nor 8088 worked.
The same config worked fine under resinOS.

**Comment by bestlibre** [comment]
Is this still an issue?

**Comment by berichta** [comment]
Didn't try it recently but about a month ago. And yes, the issue still occurs.

**Comment by tayanov** [comment]
+1. when remove vhost, all work
