### ISSUE TITLE
snapcastclient not starting

### ISSUE THREAD

**Issue by blueboysthlm** [bestlibre/hassio-addons#84]
When i try to start snapcastclient I get the following error message:

/run.sh: line 8: snapclient: command not found

**Comment by mike6460** [comment]
Did you figure this out?  I am getting the same error.

**Comment by jussbba** [comment]
Me too, any solution?

**Comment by jussbba** [comment]
Any updates on this?

**Comment by Teryeahh** [comment]
Awsome! Will try when I get home

**Comment by Teryeahh** [comment]
Not working.. Did you do anything to make it work? What Hass.io version are you running? and is the protecion mode on or off?

**Comment by jussbba** [comment]
No, I just uninstalled snapclient and the installed it again. Protection mode seems to be enabled.

Did you put ip between ” ” these? I have it that way.

I am running 0.83.3, how about you?

**Comment by Teryeahh** [comment]
Yes. I put IP between those. It is updates to the last version.. i still get the same error.. I guess this Addon is no longer maintained? No replies from the dev...?

**Comment by bestlibre** [comment]
Duplicate of #91
