### ISSUE TITLE
[Enhancement] Update for mopidy-iris

### ISSUE THREAD

**Issue by depressivum** [bestlibre/hassio-addons#93]
I'm very happy using mopidy-cast with hassio. Now im wondering if it might be possible to update mopidy-iris to an recent version or enable the built-in update mechanic (requiers root but woulnd't be a thng inside the container?)

Thank you in advance.

**Comment by bestlibre** [comment]
Can you check if the last version fix this (no built-in update, but the last version of mopidy-iris should be installed)

**Comment by bestlibre** [comment]
Please reopen if needed
